spring:
  data:
    mongodb:
      uri: mongodb://root:password111@localhost:27017/trainers_duration?authSource=admin
      database: users
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: false
    pool:
      enabled: false


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  expirationTime: 3600000
  secret: 36763979244226452948404D635166546A576D5A7134743777217A25432A462D

server:
  port: 8081
  error:
    include-message: always